version: '3'
services:
  web:
    image: tutor-match:latest
    build: .
    ports:
      - 8080:8080
    links:
      - database
    depends_on:
      - database
    environment:
      TYPEORM_CONNECTION: mysql
      TYPEORM_URL: mysql://root:B7u6AlM5rz@database:3306/tutor_match
  database:
    image: mariadb:latest
    environment:
      MYSQL_DATABASE: tutor_match
      MYSQL_ROOT_PASSWORD: B7u6AlM5rz
