# Starts a docker container for development
# This listens for http on port 8080, and listens for node debug on
# port 9229 (--inspect protocol)
# This also starts the Typescript compiler (tsc) and watches all typescript
# files for changes. When the files are changed, they will be compiled and
# then the server will restart.
version: '3'
services:
  web:
    image: tutor-match:dev
    build: 
      context: .
      dockerfile: Dockerfile-dev
    ports:
      - 8080:8080
      - 9229:9229
    links:
      - database
    depends_on:
      - database
    volumes:
      - ./:/app/
    environment:
      TYPEORM_CONNECTION: mysql
      TYPEORM_URL: mysql://root:B7u6AlM5rz@database:3306/tutor_match
  database:
    image: mariadb:latest
    ports:
      - 3366:3306
    environment:
      MYSQL_DATABASE: tutor_match
      MYSQL_ROOT_PASSWORD: B7u6AlM5rz
  adminer:
    image: adminer
    links:
      - database:db
    ports: 
      - 9000:8080
